### ISSUE TITLE
Upgrade Checklist

### ISSUE THREAD

**Issue by cmboling** [mario-campos/my-lgtm-helm-chart#3]
Still tinkering with the upgrade. I went with the GKE free tier route and setup a RDS but ran into a few issues regarding insufficient resources, which I think I can remediate by editing some of the resources in deployment configs. I ran into the same issue if I just installed 1.26. I think if it weren't for those issues, I would have been able to upgrade LGTM properly. I'll keep going at it though.

Some things I would check after an upgrade:
- [ ] Did we retain the LGTM license after upgrade?
- [ ] Did we retain users and admin permissions after upgrade?
  - [ ] Confirm that we have retained data from the previous version of LGTM?
    - [ ] Was there a proper backup (pg dump)?
    - [ ] Quick database row check on a crucial table (before and after)
    - [ ] Quick check in some settings, alerts, or queries
- [ ] Are we able to go through usual CRUD operations in the upgraded version of LGTM?
- [ ] Are we able to traceroute from cluster to external db?
